gerenciador_tarefas/app/urls.py
from django.contrib import admin
from django.urls import path
from .views.tarefas_views import *
from .views.usuarios_views import *


urlpatterns = [

    path ('listar_tarefas/', listar_tarefas, name='listar_tarefas'),
    path ('cadastrar_tarefas/', cadastrar_tarefas, name='cadastrar_tarefas'),
    path ('editar_tarefas/<int:id>/', editar_tarefas, name='editar_tarefas'),
    path ('remover_tarefas/<int:id>/', remover_tarefas, name='remover_tarefas'),
    path ('cadastrar_usuarios/', cadastrar_usuarios, name='cadastrar_usuario'),
    path ('logar_usuario/', logar_usuario, name='logar_usuario'),
    path ('deslogar_usuario/', deslogar_usuario, name='deslogar_usuario'),
]

gerenciador_tarefas/gerenciador_tarefas/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls)
]

gerenciador_tarefas/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ('A', "Alta"),
        ('N', "Normal"),
        ('B', "Baixa"),

    ]
    titulo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE )

gerenciador_tarefas/app/forms.py
from django import forms
from .models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('usuario', )
        fields = '__all__'

gerenciador_tarefas/app/views/tarefas_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from ..forms import TarefaForm
from ..entidades.tarefas import Tarefa
from ..services import tarefa_service
# Create your views herec
@login_required()
def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas(request.user)
    return render(request, 'tarefas/listar_tarefas.html', {'tarefas':tarefas})

@login_required()
def cadastrar_tarefas(request):
    if request.method == 'POST':
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo  = form_tarefa.cleaned_data['titulo']
            descricao  = form_tarefa.cleaned_data['descricao']
            data_expiracao  = form_tarefa.cleaned_data['data_expiracao']
            prioridade  = form_tarefa.cleaned_data['prioridade']
            tarefa_nova = Tarefa(titulo = titulo, descricao = descricao, data_expiracao = data_expiracao, prioridade = prioridade, usuario=request.user)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})


@login_required()
def editar_tarefas(request, id):
    tarefa_bd = tarefa_service.listar_tarefas_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse('Não permitido')
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        titulo  = form_tarefa.cleaned_data['titulo']
        descricao  = form_tarefa.cleaned_data['descricao']
        data_expiracao  = form_tarefa.cleaned_data['data_expiracao']
        prioridade  = form_tarefa.cleaned_data['prioridade']
        tarefa_nova = Tarefa(titulo = titulo, descricao = descricao, data_expiracao = data_expiracao, prioridade = prioridade)
        tarefa_service.editar_tarefas(tarefa_bd, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})

@login_required()
def remover_tarefas(request, id):
    tarefa_bd = tarefa_service.listar_tarefas_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse('Não permitido')
    if request.method == 'POST':
        tarefa_service.remover_tarefas(tarefa_bd)
        return redirect ('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_bd})

gerenciador_tarefas/app/views/usuarios_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.http import HttpResponse

def cadastrar_usuarios(request):
    if request.method == 'POST':
        form_usuario = UserCreationForm(request.POST)
        if form_usuario.is_valid():
            form_usuario.save()
            return redirect('listar_tarefas')
    else:
        form_usuario = UserCreationForm()

    return render(request, 'usuarios/form_usuario.html', {"form_usuario":form_usuario })
def logar_usuario(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('listar_tarefas')
        else:
            messages.error(request,'As credenciais do usuario estão incorretas')
            return redirect('logar_usuario')
    else:

        form_login = AuthenticationForm()
    
    return render(request, 'usuarios/login.html', {'form_login':form_login})

def deslogar_usuario(request):
    logout(request)
    return redirect('logar_usuario')

gerenciador_tarefas/app/templates/home/index.html
{% extends 'base.html' %}

{% block conteudo %}



{% endblock conteudo %}

gerenciador_tarefas/app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo %}
<div class="card-mb-3">
    <div class="card-header">
        Tem certeza que deseja remover a tarefa abaxo?
    </div>
    <div class="card-body">
        <h5 class="card-title">
            {{ tarefa.titulo }}
            
        </h5>
        <p class="card-text">
            {{ tarefa.descicao }}
        </p>
        <hr>
        <form method="POST">
            {% csrf_token %}

            <button class='btn btn-danger' type="submit">remover</button>
        </form>

    </div>
</div>
{% endblock conteudo %}

gerenciador_tarefas/app/templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}
    <form method="post">
        {% csrf_token %}
    <div class='form-group'>
        <label>Título:</label>
        {{ form_tarefa.titulo.errors }}
        {{ form_tarefa.titulo|addClass:'form-control' }}
    </div>
    <div class='form-group'>
        <label>Descrição:</label>
        {{ form_tarefa.descricao.errors }}

        {{ form_tarefa.descricao|addClass:'form-control' }}
    </div>
    <div class='form-group'>
        <label>Data de expiração:</label>
        {{ form_tarefa.data_expiracao.errors }}

        {{ form_tarefa.data_expiracao|addClass:'form-control' }}
    </div>
    <div class='form-group'>
        <label>Prioridade:</label>
        {{ form_tarefa.prioridade.errors }}

        {{ form_tarefa.prioridade|addClass:'form-control' }}
    </div>
        <input type="submit" class="form-group" value="Salvar"/>
    </form>

{% endblock conteudo %}

gerenciador_tarefas/app/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}
{% block conteudo %}
    <h1>Listagem de tarefas</h1>
    {% for tarefa in tarefas %}
    <div class="card-mb-3">
        <div class="card-header">
            {{ tarefa.get_prioridade_display }}
        </div>
        <div class="card-body">
            <h5 class="card-title">
                {{ tarefa.titulo }}
                
            </h5>
            <p class="card-text">
                {{ tarefa.descicao }}
            </p>
            <hr>
            <a href="{% url 'editar_tarefas' tarefa.id %}">Alterar Tarefas</a>
            <a href="{% url 'remover_tarefas' tarefa.id %}">Remover Tarefas</a>

        </div>
    </div>



    {% endfor %}
    <a href="{% url 'cadastrar_tarefas' %}"><input type="button" class='btn btn-primary' value='cadastrar tarefa'></a>
{% endblock conteudo %}

gerenciador_tarefas/app/templates/usuarios/form_usuario.html
{% extends 'base.html' %}
{% load meus_filtros %}
 

{% block conteudo %}

<form method="POST">
    {% csrf_token %}

    <div class="form-group">
        {{ form_usuario.username.errors }}

        <label>Username:</label>
        {{ form_usuario.username|addClass:'form-control' }}

    </div>
    <div class="form-group">
        {{ form_usuario.password1.errors }}

        <label>Senha:</label>

        {{ form_usuario.password1|addClass:'form-control' }}
    </div>
    <div class="form-group">
        {{ form_usuario.password2.errors }}

        <label>Confimar Senha:</label>
        {{ form_usuario.password2|addClass:'form-control'}}
    </div>
    <div class="form-group">
        <input type="submit"value='Cadastrar'class='btn btn-primary' >
    </div>

</form>

{% endblock conteudo %}

gerenciador_tarefas/app/templates/usuarios/login.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block conteudo %}

<form method="post">
    {% csrf_token %}
    {% for message in messages %}
        <div  class='alert alert-danger'>
            {{message}}
        </div>
    {% endfor %}

    <div class="form-group">
        <label >Nome de usuário: </label>
        {{form_login.username|addClass:'form-control'}}
    </div>
    <div class="form-group">
        <label >Senha: </label>
        {{form_login.password|addClass:'form-control'}}
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value='Entrar' >
    </div>
</form>

{% endblock conteudo %}